# Generated by Django 3.2 on 2024-05-16 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doktor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DoktorID', models.CharField(max_length=100)),
                ('Ad', models.CharField(max_length=100)),
                ('Soyad', models.CharField(max_length=100)),
                ('UzmanlikAlani', models.CharField(max_length=100)),
                ('CalistigiHastane', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hasta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('HastaID', models.CharField(max_length=100)),
                ('Ad', models.CharField(max_length=100)),
                ('Soyad', models.CharField(max_length=100)),
                ('DogumTarihi', models.DateField()),
                ('Cinsiyet', models.CharField(max_length=10)),
                ('TelefonNumarasi', models.CharField(max_length=15)),
                ('Adres', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TibbiRapor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('RaporTarihi', models.DateField()),
                ('RaporIcerigi', models.TextField()),
                ('RaporImage', models.ImageField(blank=True, upload_to='images')),
                ('Doktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.doktor')),
                ('Hasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.hasta')),
            ],
        ),
        migrations.CreateModel(
            name='Randevu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('RandevuTarihi', models.DateField()),
                ('RandevuSaati', models.CharField(max_length=10)),
                ('Doktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.doktor')),
                ('Hasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.hasta')),
            ],
        ),
    ]
